[package]
name = "prover_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive", "rc"] }
tracing = "0.1.37"
bincode = "1.3.3"
anyhow = "1.0.97"
once_cell = "1.13.0"
zstd = "0.13.3"
lru = "0.14.0"
parking_lot = "0.12"
crossbeam-channel = "0.5.12"

zkm-core-machine = { git = "https://github.com/ProjectZKM/Ziren" }
zkm-core-executor = { git = "https://github.com/ProjectZKM/Ziren" }
zkm-stark = { git = "https://github.com/ProjectZKM/Ziren" }
zkm-prover = { git = "https://github.com/ProjectZKM/Ziren" }
zkm-recursion-compiler = { git = "https://github.com/ProjectZKM/Ziren" }
zkm-recursion-core = { git = "https://github.com/ProjectZKM/Ziren" }
zkm-recursion-circuit = { git = "https://github.com/ProjectZKM/Ziren" }
zkm-sdk = { git = "https://github.com/ProjectZKM/Ziren" }

p3-maybe-rayon = { git = "https://github.com/ProjectZKM/Plonky3" }

zkm-gpu-prover = { git = "https://github.com/ProjectZKM/ziren-gpu", optional = true }
zkm-gpu-core = { git = "https://github.com/ProjectZKM/ziren-gpu", optional = true }

common = { path = "../common" }
tempfile = "3.18.0"
lazy_static = "1.5.0"

[features]
debug = []
gpu = ["dep:zkm-gpu-prover", "dep:zkm-gpu-core", "zkm-gpu-core/pinned-pages"]